# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: barbican
  type: group
  role: [barbican]
  required_for: [deploy_end]
  requires: [firewall]
  tasks: [hiera, fuel_pkgs, globals, tools, logging,
    netconfig, hosts, firewall]
  parameters:
    strategy:
      type: parallel

- id: primary-barbican
  type: group
  role: [primary-barbican]
  required_for: [deploy_end]
  requires: [firewall]
  tasks: [hiera, fuel_pkgs, globals, tools, logging,
    netconfig, hosts, firewall]
  parameters:
    strategy:
      type: one_by_one

#- id: fuel-plugin-barbican-deployment-puppet
#  type: puppet
#  role: [fuel-plugin-barbican_role]
#  requires: [deploy_start]
#  required_for: [deploy_end]


#  version: 2.0.0              # tasks v2.0.0 is supporting task-based deployment
#   cross-depends:
#     - name: deploy_start
#   cross-depended-by:
#     - name: deploy_end

#  parameters:
#    puppet_manifest: "deploy.pp"
#    puppet_modules: "."
#    timeout: 3600

- id: barbican_db
  type: puppet
  groups: [primary-barbican, barbican]
  requires: [primary-controller]
  required_for: [barbican_openstack]
  parameters:
    puppet_manifest: puppet/manifests/db_barbican.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 3600
    cwd: /etc/fuel/plugins/barbican-1.0

- id: barbican_firewall
  type: puppet
  groups: [primary-barbican, barbican]
  requires: [netconfig]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/firewall.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 3600
    cwd: /etc/fuel/plugins/barbican-1.0

- id: barbican_haproxy
  type: puppet
  groups: [primary-controller, controller]
  requires: [deploy_start, primary-cluster-haproxy, cluster-haproxy]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/openstack-haproxy-barbican.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 3600
    cwd: /etc/fuel/plugins/barbican-1.0

- id: barbican_openstack
  type: puppet
  groups: [primary-barbican, barbican]
  requires: [barbican_db]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/openstack_barbican.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 3600
    cwd: /etc/fuel/plugins/barbican-1.0

- id: barbican_keystone
  type: puppet
  groups: [primary-controller]
  requires: [primary-keystone]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/keystone.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 3600
    cwd: /etc/fuel/plugins/barbican-1.0

- id: barbican_keystone_hook
  type: puppet
  groups: [primary-barbican, barbican]
  requires: [barbican_openstack]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: puppet/manifests/barbican_keystone_hook.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 3600
    cwd: /etc/fuel/plugins/barbican-1.0

- id: compute_contrail_hook
  version: 2.0.0
  type: puppet
  role: [compute]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  condition: "settings:barbican.use_contrail.value == true"
  parameters:
    puppet_manifest: puppet/manifests/vrouter.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 60
